name: first_aid_app
description: App de primeros auxilios con Firebase
publish_to: "none"
version: 0.0.3

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.6
  
  sqflite: ^2.2.8+1
  path: ^1.8.3
  path_provider: ^2.0.14
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # ← AGREGA ESTA LÍNEA

flutter:
  uses-material-design: true
  assets:
    - assets/images/